FROM golang:1.22.2-alpine3.19 AS builder

RUN apk add --no-cache ca-certificates && update-ca-certificates

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download
RUN go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/server ./cmd/traefik-github-oauth-server

WORKDIR /app

EXPOSE 80

ENTRYPOINT ["/app/server"]
